#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 20200606 - Created script to backup Nextcloud
# 20200607 - Updated script with tar compression
#
echo "--------------------------------"
echo "--[ Turn on Maintenance Mode ]--"
echo "--------------------------------"
sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --on
sudo mount -t cifs //10.0.100.10/NNVault /nnvault -o credentials=/home/nn/.smbnnvault
echo "-----------------------------------"
echo "--[ Backup /nextcloud directory ]--"
echo "-----------------------------------"
sudo mkdir /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud/
sudo rsync -azxh --inplace --info=progress2 --stats --exclude 'data/nn' /var/www/nextcloud/ /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud/
sudo tar -czf /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud.tar.gz /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud/
sudo rm -r /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud/
echo "-------------------------------"
echo "--[ Backup MariaDB Database ]--"
echo "-------------------------------"
sudo mysqldump --single-transaction -u nextclouduser nextcloud > /home/nn/nextcloud_backup.bak
#Shift around to create a dated backup
sudo mv /home/nn/nextcloud_backup.bak /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud_backup.bak
sudo mkdir /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud_backup
sudo mv /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud.tar.gz /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud_backup/nextcloud.tar.gz
sudo mv /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud_backup.bak /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud_backup/nextcloud_backup.bak
sudo mv /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud_backup /nnvault/Backup/NNServer/WEB.NextCloud/backup/nextcloud_backup_`date +"%Y-%m-%d_%H%M%S"`/
echo "-------------------"
echo "--[ Cleaning up ]--"
echo "-------------------"
sudo umount -t cifs //10.0.100.10/NNVault
sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off