#!/bin/bash
#   _  ___  __                         
#  / |/ / |/ /
# /    /    /   
#/_/|_/_/|_/  
#
# 20200529 - First script for updating NextCloud VM
# 20220118 - Update script, added nextcloud updating
#
echo "------------------------------------------"
echo "--[ Debian Version $(cat /etc/debian_version), Update? (y/n) ]--"
echo "------------------------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "-----------------------"
  echo "--[ Updating Debian ]--"
  echo "-----------------------"
  sudo apt update
  echo "------------------------"
  echo "--[ Upgrading Debian ]--"
  echo "------------------------"
  sudo apt upgrade
  echo "-------------------------"
  echo "--[ Running autoclean ]--"
  echo "-------------------------"
  sudo apt autoclean
  echo "--------------------------"
  echo "--[ Running autoremove ]--"
  echo "--------------------------"
  sudo apt autoremove
fi
echo "-------------------------------"
echo "--[ Update Nextcloud? (y/n) ]--"
echo "-------------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "------------------------"
  echo "--[ Updating Nextcloud ]--"
  echo "------------------------"
  sudo -u www-data php /var/www/nextcloud/updater/updater.phar
fi
echo "-------------------------"
echo "--[ Check Logs? (y/n) ]--"
echo "-------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "---------------------------------------"
  echo "--[ Checking Unattended Updates log ]--"
  echo "---------------------------------------"
  sudo tail -n 5 /var/log/unattended-upgrades/unattended-upgrades.log
  echo "---------------------------------------"
  echo "--[ Checking if fail2ban is running ]--"
  echo "---------------------------------------"
  sudo fail2ban-client status
  echo "---------------------------"
  echo "--[ Checking UFW status ]--"
  echo "---------------------------"
  sudo ufw status
  echo "--------------------------------------"
  echo "--[ Check Disk Access Speed? (y/n) ]--"
  echo "--------------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "---------------------------------"
    echo "--[ Testing disk access speed ]--"
    echo "---------------------------------"
    sudo hdparm -tT /dev/sda1
  fi
  echo "--------------------------------"
  echo "--[ Run rkhunter scan? (y/n) ]--"
  echo "--------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
  echo "-----------------------------"
  echo "--[ Running rkhunter scan ]--"
  echo "-----------------------------"
  sudo rkhunter --check --rwo
  fi
fi